# $ micromamba create -f environment.yml
# $ micromamba activate solvisenv
#

name: solvisenv
channels:
  - conda-forge
# requirements:
#   build:
#     - {{ compiler('c') }}
#     - {{ compiler('c++') }}
dependencies:
  - python>=3.10
  - python-build
  - ase>=3.22.1
  - numpy>=1.26.4 # 1.22.4
  - scipy>=1.7.3
  - ipython>=8.26.0
  - pandas>=2.2.2
  - pyvista>=0.43.0
  - pytest-pyvista
  # Dependencies for pyvista
  - vtk>=9.2.6
  - pillow>=10.0.1
  - imageio>=2.31.5
  - pooch>=1.8.0
  - scooby>=0.9.2
  # Packaging
  - twine
  - flit>=3.9.0
  - pytest>=6.2.5
  - coverage>=6.1.1
  - pytest-cov>=3.0.0
  - flake8>=3.9.2
  - mypy>=0.910
  - black>=22.3.0
  - isort>=5.9.3
  - autoflake>=1.4
  - flake8-docstrings>=1.6.0 
  - meson-python>=0.16.0
  - pytest-cov>=3.0.0
  # - pip:
  #   # works for regular pip packages
  #   - lammps-logfile
